let mongoose = require('mongoose')

let allRightModule = new mongoose.Schema({
 empId:String,
 empName:String,
 memBerId:String,
 email:String,
 emailUniqId:String,
 crmRights:{
    crmDashboard:{
        value:Boolean,
        rights:[]
    },
    crmEmployee:{
        value:Boolean,
        items:{
            crmDashboard1:{
                value:Boolean,
               rights:[]
            },
            crmEmployeeTarget1:{
                value:Boolean,
                rights:[]
            },
            crmMemberCalls1:{
                value:Boolean,
                rights:[]
            },crmSalesCall1:{
                value:Boolean,
                rights:[]
            },crmServicesRateCard1:{
                value:Boolean
            }
        }
    },
    crmTrainer:{
        value:Boolean,
        items:{
            superRight:{
                dailybatchAttendance:[],
                monthlyReport:[],
                clientAttendanceReg:[]
            },    
            crmLiveClasses1:{
                value:Boolean
            },
            crmAllBatches1:{
                value:Boolean
            },
            crmPtClasses1:{
                value:Boolean
            },
            crmTtcClasses:{
                value:Boolean
            },
            crmAllMembers1:{
                value:Boolean
            }
        }
    },
    crmLeads:{
        value:Boolean,
        items:{
            superRight:{
                addOn:[],
                delete:[],
                edit:[]
            },
            crmAllEnquiry1:{
                value:Boolean,
            },
            crmAppointment1:{
                value:Boolean,
            },
            crmTrialUpdate1:{
                value:Boolean,
            },
            crmProspects1:{
                value:Boolean,
            },
            crmCallsReports1:{
                value:Boolean,
            },
            crmColdEnquires1:{
                value:Boolean,
            }
        }
    },
    crmCientManagment:{
        value:Boolean,
        items:{
            superRight:{
                delete:[],
                edit:[],
                status:[],
                profile:[]
            },
            crmAllClients1:{
                value:Boolean,
            },
            crmActiveClients1:{
                value:Boolean,
            },
            crmRenewalsClient1:{
                value:Boolean,
            },
            crmRenewedClients1:{
                value:Boolean,
            },
            crmLeftClients1:{
                value:Boolean,
            },
            crmClientSupport1:{
                value:Boolean,
            }
        }
    },
    crmMarketing:{
        value:Boolean,
        items:{
            superRight:{
                addOn:[],
                delete:[],
                edit:[],
                status:[],
            },
            crmEmailMarketing1:{
                value:Boolean
            },
            crmSmsMarketing1:{
                value:Boolean
            },
            crmPushMarketing1:{
                value:Boolean
            },
            crmBulkMailerData1:{
                value:Boolean
            },
            crmBulkCallingData1:{
                value:Boolean
            },
            crmCustomerReview1:{
                value:Boolean
            },
            crmOffersMaster1:{
             value:Boolean
            }
        }
    },
    crmFitness:{
        value:Boolean,
         superRight:{
            addOn:[],
            delete:[],
            edit:[],
            access:[],
        },
        items:{
            crmFitnessGoal:{
                value:Boolean,
                rights:[]
            }
        }
    }
 },
 erpRights:{
  erpTaskList:{
    value:Boolean,
    items:{
        erpTaskListCalender:{
            value:Boolean,
            rights:[]
        }
    }
  },
  erpInventory:{
    value:Boolean,
    items:{
        erpStockList:{
            value:Boolean,
            rights:[]
        },
        erpStockReport:{
            value:Boolean,
            rights:[]
        },
        erpProductList:{
            value:Boolean,
            rights:[]
        },
        erpStockAlert:{
            value:Boolean,
            rights:[]
        },
        erpProductSalesReport:{
            value:Boolean,
            rights:[]
        },
        erpOfficeInventory:{
            value:Boolean,
            rights:[]
        },
        erpImpCallList:{
            value:Boolean,
            rights:[]
        },
        erpProductInvoice:{
            value:Boolean,
            rights:[]
        }
    }
  },
  erpFinance:{
    value:Boolean,
    items:{
        erpInvoices:{
            value:Boolean,
            items:{
                erpTotalInvoice:{
                    value:Boolean,
                    rights:[]

                },
                erpPaidInvoice:{
                    value:Boolean,
                    rights:[]
                },
                erpBalancePayment:{
                    value:Boolean,
                    rights:[]
                },
                erpReceipts:{
                    value:Boolean,
                    rights:[]
                },
                erpCancelledInvoice:{
                    value:Boolean,
                    rights:[]
                },
                erpCommentsOfWrittenOffInvoice:{
                    value:Boolean,
                    rights:[]
                }
                
            }
            
        },
        erpRevenues:{
        value:Boolean,
        items:{
            erpRevenueDetails:{
                value:Boolean,
                rights:[]
            },
            erpServicesWiseRevenue:{
                value:Boolean,
                rights:[]

            },
            erpNewClientRevenue:{
                value:Boolean,
                rights:[]
            },
            erpRenewalsRevenue:{
                value:Boolean,
                rights:[]

            },
            erpLeadReport:{
                value:Boolean,
                rights:[]

            },
            erpRevenueReport:{
                value:Boolean,
                rights:[]
            }
        }
        },
        erpCollectionReport:{
            value:Boolean,
            items:{
                erpTotalCollection:{
                 value:Boolean,
                 rights:[]
                },
                erpPaymentMode:{
                 value:Boolean,
                 rights:[]
                },
                erpCashReport:{
                 value:Boolean,
                 rights:[]
                },
                erpChequeReport:{
                 value:Boolean,
                 rights:[]
                }
            }
        },
        erpExpense:{
         value:Boolean,
         items:{
            erpCenterExpense:{
                value:Boolean,
                rights:[]
            },
            erpDailyExpense:{
                value:Boolean,
                rights:[]
            },
            erpPettyCash:{
                value:Boolean,
                rights:[]
            }
         }     
        },
        erpSales:{
         value:Boolean,
         items:{
            erpDsrReport:{
                value:Boolean,
                rights:[]
            },
            erpTargetVsAchievment:{
                value:Boolean,
                rights:[]
            }
         }
        } 

    }
  },
  erpHrManagement:{
    value:Boolean,
    items:{
        erpRecuritment:{
            value:Boolean,
            rights:[]
        },
        empLoyeeHrProfile:{
            value:Boolean,
            items:{
                erpEmployeeProfile:{
                    value:Boolean,
                    rights:[]
                },
                erpEmployeeDocuments:{
                    value:Boolean,  
                    rights:[]
                },
                erpJobProfile:{
                    value:Boolean,   
                    rights:[]  
                }
            }
        },
        erpHrTargetSheet:{
            value:Boolean,
            items:{
                erpTargetSheet:{
                    value:Boolean,
                    rights:[]

                },
                erpEmpPerformance:{
                    value:Boolean,
                    rights:[]
                }
            }
        },
        erpEmpAttendess:{
          value:Boolean,
          items:{
            erpEmpCheckIns:{
                value:Boolean,
                rights:[]
            },
            erpBiometricEmp:{
                value:Boolean,
                rights:[]
            },
            erpEmpAttedanceRegister:{
                value:Boolean,
                rights:[]
            }
          }
   
        },
        erpHrHrPolicy:{
            value:Boolean,
            items:{
                erpHrPolicy:{
                    value:Boolean,
                    rights:[]
                },
                erpHolidayList:{
                    value:Boolean,
                    rights:[]
                },
                erpShiftTiming:{
                    value:Boolean,
                    rights:[]  
                },
                erpEmpJoing:{
                    value:Boolean,   
                    rights:[] 
                }  
            }
        },
        erpSalarySheet:{
            value:Boolean,
            items:{
                erpLeaveSetup:{
                    value:Boolean,
                    rights:[]
                },
                erpEmpSalarySheet:{
                    value:Boolean,
                    rights:[]
                },
                erpTrainerSalarySlip:{
                    value:Boolean,
                    rights:[]
                },
                erpAllTrainerReport:{
                    value:Boolean,
                    rights:[]
                }
            }
        },
        erpAllRights:{
            value:Boolean,
            rights:[]
        },
    }
  },
  erpCourse:{
    eximpRights:[],
    value:Boolean,
    items:{
        erpTTCClients:{
         value:Boolean,
         rights:[]
        },
        erpTTCVideos:{
         value:Boolean,
         rights:[]
        },
        erpTTCPdf:{
         value:Boolean,
         rights:[]
        },
        erpCourseCompletion:{
         value:Boolean,
         rights:[]
        }
    }
  }
 },
 masterRights:{
    masterCenterSetup:{
        value:Boolean,
        items:{
            masterCompanyLogoSetup:{
                value:Boolean,
                rights:[]
            },
            masterCompanyProfileSetup:{
                value:Boolean,
                rights:[]  
            },
            masterServicesMaster:{
                value:Boolean,
                rights:[]  
            },
            masterPackageMaster:{
                value:Boolean,
                rights:[]  
            },
            masterBatchTimeMaster:{
                value:Boolean,
                rights:[] 
            },
            masterFormMaster:{
                value:Boolean,
                rights:[] 
            },
            masterInvoiceMaster:{
                value:Boolean,
                rights:[] 
            }

        }
    },
    masterClientFeedback:{
       value:Boolean,
       rights:[]      
    },
    masterMarketing:{
        value:Boolean,
        items:{
            masterLeadSourseMaster:{
                value:Boolean,
                rights:[]       
            },
            masterSmsEmailTemp:{
                value:Boolean,
                rights:[]     
            },
            masterGallertyMaster:{
                value:Boolean,
                rights:[]    
            },
            masterAutomatedComToStaff:{
                value:Boolean,
                rights:[]     
            }
        }
    },
    masterClient:{
        value:Boolean,
        items:{
      masterClientTransferMaster:{
        value:Boolean,
        rights:[]      
      }
    }   
    },
    masterHr:{
        value:Boolean,
        items:{
            masterEmployeeDesignation:{
             value:Boolean,
             rights:[]    
            },
            masterHrPolicy:{
             value:Boolean,
             rights:[]   
            },
            masterHolidaysList:{
                value:Boolean,
                rights:[]     
            },
            masterEmpJoining:{
                value:Boolean,
                rights:[]    
            },
            masterJobProfile:{
                value:Boolean,
                rights:[]     
            },
            masterEmployeeDocument:{
                value:Boolean,
                rights:[] 
            },
            masterLeaveSetup:{
                value:Boolean,
                rights:[]  
            },
            masterSalarySheet:{
                value:Boolean,
                rights:[] 
            },
            masterShiftTiming:{
                value:Boolean,
                rights:[] 
            },
            masterTrainerSalarySlip:{
                value:Boolean,
                rights:[]    
            },
            masterEmpPrformance:{
                value:Boolean,
                rights:[]  
            }
        } 
    },
    masterInverntory:{
        value:Boolean,
        items:{
            masterAllProductListingMaster:{
                value:Boolean,
                rights:[]  
            },
            masterOfficeInventory:{
                value:Boolean,
                rights:[]  
            }
        } 
    },
    masterFinance:{
        value:Boolean,
        items:{
            masterExpnessCategor:{
                value:Boolean,
                rights:[]
            },
            masterBudgeting:{
                value:Boolean,
                rights:[]
            },
            masterInvoiceSetupMaster:{
                value:Boolean,
                rights:[] 
            },
            masterTaxSetupMaster:{
                value:Boolean,
                rights:[]  
            }
        }
    },
    masterCenterPartners:{
        value:Boolean,
        rights:[]
    }
 }
}, { timestamps: Boolean })

module.exports = mongoose.model('allRightModule', allRightModule);
