let mongoose = require('mongoose')


let enquiryForms = new mongoose.Schema({
    username: String,
    EnquiryId: String,
    Fullname: String,
    Emailaddress: String,
    CountryCode: Number,
    ContactNumber: {
        type:Number,
        unique:true,
    },
    Gander: String,
    DateofBirth: Date,
    address: String,
    Area: String,
    city: String,
    Profession: String,
    StaffName: String,
    CenterName: String,
    CallStatus: String,
    Message: String,
    person_Name: String,
    Relation: String,
    CountryCode2: Number,
    ContactNumber2: Number,
    EnquiryDate: Date,
    ServiceName: String,
    ServiceVariation: String,
    Customertype: String,
    enquirytype: String,
    appointmentDate: Date,
    appointmentTime: String,
    appointmentfor: String,
    trialDate: Date,
    trialTime: String,
    Counseller: String,
    status: String,
    identifyStage:String,
    enquirestatus:String,
    ClientReferenceName:String,
    ClientReferrenceId:mongoose.Schema.Types.ObjectId,
    EmployeeId:String,
    enquiryConvertedDate:Date,
    invEmployeeId:String,
    invEmployeeName:String,
    invoiceId:String,
    trailStatus:Boolean,
    empNameC:String,
    employeeIDC:String,
    employeeMongoId: mongoose.Schema.Types.ObjectId,
    partnerAdminMongoId: mongoose.Schema.Types.ObjectId,
    createdAt:Date,
    centerNameC:String,
    centerCodeC:String,
    adminNameC:String,
    PFollowupDate:String,
    PDiscussion:String,
    PTimeFollowp:String,       
    PAppointmentTime: String,
    PAppointmentDate: String,
    PServiceName: String, 
    PCallDate: String, 
    PTime: String,
    PName: String, 
    PContact: String,
    PEmail: String,
    image: String
}, { timestamps: true })

module.exports = mongoose.model('enquiryForms', enquiryForms);
